[package]
name = "deeper"
version = "0.0.1"
authors = ["Arnaldur Bjarnason <aarnaldur@gmail.com>", "Jökull Reynisson <jokullmani12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# dung_gen
rand = "0.7"
ena  = "0.13.1"

# graphics and input
cgmath        = "0.17"
winit         = "0.22"
wgpu          = { git = "https://github.com/gfx-rs/wgpu-rs.git", branch = "master" }
futures       = "0.3"
env_logger    = "0.7"
glsl-to-spirv = "0.1"
zerocopy = "0.3"
wavefront_obj = "*"
lazy_static = "1.4.0"

# json stuff
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# ECS
specs = { version = "0.16.1", features = ["specs-derive"] }

