[package]
name = "deeper"
version = "0.0.1"
authors = ["Arnaldur Bjarnason <aarnaldur@gmail.com>", "Jökull Reynisson <jokullmani12@gmail.com>"]
edition = "2018"

[profile.release]
opt-level = 2
incremental = true
lto = false
#lto = "thin"

[dependencies]

# misc
itertools = "0.10"

# dung_gen
rand = "0.8.3"
ena  = "0.14.0"

# graphics and input
# wgpu          = { git = "https://github.com/gfx-rs/wgpu-rs.git", branch = "master" }
wgpu          = "0.6"
cgmath        = "0.18"
winit         = "0.24"
futures       = "0.3"
env_logger    = "0.8.2"
shaderc       = "0.7.1"
zerocopy      = "0.3"
lazy_static   = "1.4.0"
imgui         = "0.6"
imgui-wgpu    = "0.12.0"
imgui-winit-support = "0.6"

wavefront_obj = "*"
gltf = "0.15.2"

# loader
ron = "*"
serde = { version = "1.0", features = ["derive"] }
notify = "4.0.15"

# ECS
legion = "0.3.1"
crossbeam-channel = "0.4.4"

# physics
nalgebra = "0.24.0"
ncollide2d = "0.27.0"
nphysics2d = "0.19.0"