[package]
name = "application"
version = "0.1.0"
authors = ["Arnaldur Bjarnason <aarnaldur@gmail.com>", "Jökull Reynisson <jokullmani12@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

winit = "0.24.0"
legion = "0.4.0"
apply = "0.3.0"
enum-map = "1.0.0"
itertools = "0.10.0"